### ISSUE TITLE
Maximum reading is 2937.60 lux

### ISSUE THREAD

**Issue by szerwi** [dantudose/MAX44009#1]
Hi,

I got this sensor from Aliexpress, but the maximum reading I can get on your library is 2937.60 lux, even though I am pointing a flashlight directly on the sensor. The same issue is happening on other libraries. The datasheet of this sensor says it can read up to 180k lux. Do you know why I can get only 2937lux read?

**Comment by dantudose** [comment]
Hi Piotr,

That's weird, have you tried with another identical sensor? Might be a bad sensor. 
What's your hardware setup? Please also attach a code example.

**Comment by szerwi** [comment]
I have this sensor.
![Przechwytywanie](https://user-images.githubusercontent.com/19311511/57300601-72ee2500-70d7-11e9-9221-59d41be51513.PNG)

I have connected it to 3.3V Arduino Pro Micro. I am using example from your library. I have the second unit of this sensor, I will check it later.

**Comment by szerwi** [comment]
@dantudose I have checked the other unit and the problem is exactly the same.

**Comment by szerwi** [comment]
I also checked the sensor with ESP32, but the problem is the same.

**Comment by szerwi** [comment]
I found out that this library is working correctly: https://github.com/NorthernWidget/MAX44009
On that library reading are similar to readings from BH1750 sensor.

**Comment by koosiekloek** [comment]
hi @szerwi 
i also got the same problem as you did with max LUX reading of 2937.60
i did some debugging through serial and seems the register read is faulty check below

  // Start I2C Transmission
  Wire.beginTransmission(Addr);
  // Select data register
  Wire.write(0x03);
  // Stop I2C transmission
  Wire.endTransmission();

  // Request 2 bytes of data
  Wire.requestFrom(Addr, 2);

  // Read 2 bytes of data
  // luminance msb, luminance lsb
  if (Wire.available() == 2)
  {
    data[0] = Wire.read();/////////////////All is well up to here when it reads here both data[0] and data[1] 
    data[1] = Wire.read();/////////////////have the same value witch is not correct!
  }

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

i changed my code to the following and it worked, reads direct sunlight up to 
Ambient Light luminance :79257.60 lux             // from serial monitor

// Start I2C Transmission
  Wire.beginTransmission(Addr);
  // Select data register
  Wire.write(0x03);
  // Stop I2C transmission
  Wire.endTransmission();

  // Request 2 bytes of data
  Wire.requestFrom(Addr, 1);

  // Read 2 bytes of data
  // luminance msb, luminance lsb
  if (Wire.available() == 1)
  {
    data[0] = Wire.read();
  } 
  Wire.beginTransmission(Addr);
  // Select data register
  Wire.write(0x04);
  // Stop I2C transmission
  Wire.endTransmission();

  // Request 2 bytes of data
  Wire.requestFrom(Addr, 1);

  // Read 2 bytes of data
  // luminance msb, luminance lsb
  if (Wire.available() == 1)
  {
    data[1] = Wire.read();
  }

**Comment by koosiekloek** [comment]
@szerwi 
i am using "Pololu A-Star 328PB Micro - 3.3V, 8MHz" micro controller
witch is the same AVR micro as the "3.3V Arduino Pro Micro" you are using.
my MAX44009 is also the exact same one you posted a pic of

**Comment by ada-lambrecht** [comment]
I'm having the same issue and it looks like the problem is in the begin function.

https://github.com/dantudose/MAX44009/blob/882e518c57c1ef360e6174e6751fa4e9d60beb4f/src/MAX44009.cpp#L6-L12

Line 10 looks like the problem. I can't find a setting in the MAX44009 datasheet for 0x40. Changing this line to ```Wire.write(0x00);``` fixed the issue for me.

I can submit a pull request with the change.

**Comment by ruzanow** [comment]
> I can't find a setting in the MAX44009 datasheet for 0x40
As I understand it, this setting enables Manual mode (BIT 6 is set), but it's not configured. Need 0x80 or 0x00

**Comment by dantudose** [comment]
Hi,

Changed to Wire.write(0x00). Issue fixed.

**Comment by RobTillaart** [comment]
> I can't find a setting in the MAX44009 datasheet for 0x40

The value 0x40 is not literally in the datasheet, it is bit 6 [MANUAL] of the control register (0x02).
The real problem seems to me the reading of the 2 bytes as stated by @koosiekloek 

[update]
2937.60 Lux implies that the registers hold 2937.60 / 0.045 = 65280 = 0xFFF0, so near max value of 0xFFFF. In the automatic mode the chip adapts integration timing so if manual mode was selected it will not adjust integration timing so it (nearly?) hits the 16 bit ceiling.

**Comment by steverimbey** [comment]
I have opened an issue before seeing this closed issue.

It appears the lux calculation in MAX4409.cpp may need correction.

Steve Rimbey
