### ISSUE TITLE
Reading method is probably incorrect according to datasheet.

### ISSUE THREAD

**Issue by typie2** [dantudose/MAX44009#2]
Hi,
There has already been an issue concerning the configuration of the MAX44009 in the begin() method. This issue was solved (you changed the manual integration time of 800ms to auto mode). However, it looks like the reading method get_lux() is still not 100% correct.
```C
Wire.beginTransmission(MAX_ADDR);
Wire.write(0x03); //here you request data from 0x03 (the Lux High-Byte Register)
Wire.endTransmission();

// You request two bytes of data (the register will only hold one byte)
Wire.requestFrom(MAX_ADDR, 2);
 
// and read this same byte into two variables 
if (Wire.available() == 2)
{
    	data[0] = Wire.read();
    	data[1] = Wire.read();
}
```
According to the datasheet ([Source](https://datasheets.maximintegrated.com/en/ds/MAX44009.pdf)), Register 0x03 contains the four bits of the exponent followed by the **four most significant bits** of the mantisa.
If you only want to use this data, the formula for lux calculation should be:

> Lux = 2^(exponent) x mantissa x 0.72

The code would look like this:
```C
float MAX44009::get_lux(void)
{
	unsigned int data;
	
	Wire.beginTransmission(MAX_ADDR);
	Wire.write(0x03);
	Wire.endTransmission();
 
	// Request 1 byte of data
	Wire.requestFrom(MAX_ADDR, 1);
 
	// Read 1 byte of data
	if (Wire.available() == 1)
	{
    		data = Wire.read();
	}
 
	// Convert the data to lux
	int exponent = (data & 0xF0) >> 4;
	int mantissa = (data & 0x0F) << 4);
	
	float luminance = pow(2, exponent) * mantissa * 0.72;
  
	return luminance; 
}
```
If you now want to achieve more precision, you can also read Register 0x04 (the Lux Low-Byte Register). This one contains the four least significant bits of the mantissa. If you put those two together, you can use the already implemented formula. The code could look similar to this:
```C
float MAX44009::get_lux(void)
{
	unsigned int data[2];
	
	Wire.beginTransmission(MAX_ADDR);
	Wire.write(0x03); //request high-byte register data
	Wire.endTransmission();

	// Request 1 byte of data
	Wire.requestFrom(MAX_ADDR, 1);

	// Read first byte of data
	if (Wire.available() == 1)
	{
    		data[0] = Wire.read();
	}

        Wire.beginTransmission(MAX_ADDR);
	Wire.write(0x04); //request low-byte register data
	Wire.endTransmission();

	// Request 1 byte of data
	Wire.requestFrom(MAX_ADDR, 1);

	// Read second byte of data
	if (Wire.available() == 1)
	{
    		data[1] = Wire.read();
	}
 
	// Convert the data to lux
	int exponent = (data & 0xF0) >> 4;
	int mantissa = ((data[0] & 0x0F) << 4) | (data[1] & 0x0F);
	
	float luminance = pow(2, exponent) * mantissa * 0.045;
  
	return luminance; 
}
```
I hope there are no mistakes in my sample code but I think this sould be the right way according to the datasheet.

**Comment by dantudose** [comment]
Thank you! Fixed.
