### ISSUE TITLE
Lux calculation

### ISSUE THREAD

**Issue by steverimbey** [dantudose/MAX44009#3]
In MAX44009.cpp It appears that the exponent is being applied to the value 1 (x00000001). The data sheet says it should be applied to value 2 which would be (x00000010).

Changing it to 2 results in a much wider range of lux values being returned.

Steve Rimbey

**Comment by dantudose** [comment]
Not sure what you mean by this... if you are referring to the line:

_float luminance = (float)(((0x00000001 << exponent) * (float)mantissa) * 0.045);_

,then by shifting 2 to the left by the exponent value you're getting one order of magnitude higher results than normal. Arguably it's a wider range, but it's not measuring lux anymore...

Alternatively you can uncomment the line above and use the pow() function, it's going to give you the same results only, depending on the compiler and optimizations, it might be slower.

**Comment by steverimbey** [comment]
Here is link to data sheet and and extract showing the lux calculation that i found. Also a suggestion about how to read the 2 registers that I have not tried yet.

MAX44009 Datasheet extract. 

Steve

https://datasheets.maximintegrated.com/en/ds/MAX44009.pdf

Bits in Lux Low-Byte register 0x04 give the 4 least significant bits of the mantissa byte representing the lux reading of ambient light. Combined with the Lux High-Byte register 0x03, it extends the resolution and dynamic range of lux measurements of the IC. E3–E0: Exponent bits of lux reading 
M7–M0: Mantissa byte of lux reading Lux = 2(exponent) x mantissa x 0.045 Exponent = 8xE3 + 4xE2 + 2xE1 + E0 Mantissa = 128xM7 + 64xM6 + 32xM5 + 16xM4 + 8xM3 + 4xM2 + 2xM1 + M0 Combining contents of register 0x03 and 0x04: 
A code of 0000 0000 0001 calculates to be 0.045 lux. A code of 0000 0001 0000 calculates to be 0.72 lux. A code of 0001 0001 0001 calculates to be 0.765 lux. A code of 1110 1111 1111 calculates to be 188,006 lux. A code of 1110 1111 1110 calculates to be 187,269 lux. 
The Lux High-Byte 0x03 and Lux Low-Byte 0x04 register updates are internally disabled at the start of a valid address transmission from the master. Updating reinitiates at the next valid STOP condition. This prevents erroneous readings in the event an update occurs between readings of registers 0x03 and 0x04. 
Update of the contents of this register is internally disabled during I2C read operations to ensure proper data transfer between internal ADC and I2C registers. Update of I2C registers is resumed when the master sends a STOP command. 
If the user wants to read both the Lux High-Byte register 0x03 and Lux Low-Byte register 0x04, then the master should not send a STOP command between the reads of the two registers. Instead a Repeated START command should be used. This ensures accurate data is obtained from the I2C registers (by disabling internal updates during the read process).

**Comment by dantudose** [comment]
Not sure how this ties in to your initial comment about shifting with 2 instead of 1. I've read the datasheet and I don't see how that is the case, it clearly states the result is computed as 2 ^ (exponent) x mantissa x constant, which is exactly what the line of code does.

**Comment by steverimbey** [comment]
My mistake, sorry. I was investigating why the lux value was so low even when shining very bright light at the sensor. Datasheet says range is 0 to 188,000ish and in only saw maxi 7000ish (don't remember the exact values but others have reported similar results).

My apologies for misreading code.

Steve Rimbey

**Comment by steverimbey** [comment]
Dan, I had initially loaded your library from the arduino ide library manager. It was NOT the same as the code here on GitHub. After getting the latest library, all is well and works as expected with the proper range of values.

Thank you for putting in the effort to develop this library and again, my apologies for having an old level of code.  Next time I load a library from arduino library manager I will check with GitHub to be safe.

Steve Rimbey

**Comment by dantudose** [comment]
No worries, glad it worked. Maybe update the library from the IDE, I made a new release a few weeks ago that fixed some issues.
